[package]
name = "mc"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/IvanUkhov/mc"
homepage = "https://github.com/IvanUkhov/mc"
description = "MC."
